/* Podcast episodes — audio hosted on Cloudflare R2, streamed directly (no bundling).
   `file` is the exact R2 object key (relative to BASE); encoded at request time. */
window.__PODCASTS_BASE = 'https://audio.ainadara.com/Notebook%20llm%20audios/';
window.__PODCASTS = [
  { file: 'Acute_Care_Cardiology_Critical_Decision_Points.m4a', title: 'Acute Care Cardiology: Critical Decision Points', blurb: 'ACS, STEMI/NSTEMI management, and the decision points that separate the right call from the textbook one.', area: 'Cardiovascular' },
  { file: 'Cardiology_Mastery_Heart_Failure_AF_Pharmacotherapy.m4a', title: 'Cardiology Mastery: Heart Failure & AFib Pharmacotherapy', blurb: 'GDMT for HFrEF, rate vs. rhythm control, and anticoagulation decisions in atrial fibrillation.', area: 'Cardiovascular' },
  { file: 'Anticoagulation_Dosing_Reversal_and_Guidelines.m4a', title: 'Anticoagulation: Dosing, Reversal, and Guidelines', blurb: 'DOACs vs. warfarin, renal dosing thresholds, and what to do when a patient bleeds.', area: 'Cardiovascular' },
  { file: 'Auditing_Cirrhosis_Bleeds_and_Crohn_s_Pharmacotherapy.m4a', title: "Auditing Cirrhosis, Bleeds, and Crohn's Pharmacotherapy", blurb: 'Variceal bleed management, hepatic dosing, and IBD pharmacotherapy audited case by case.', area: 'GI/Hepatology' },
  { file: 'The_Clinical_Gauntlet_of_Fluids_and_Electrolytes.m4a', title: 'The Clinical Gauntlet of Fluids and Electrolytes', blurb: 'Sodium, potassium, and fluid management when the numbers and the patient disagree.', area: 'Critical Care' },
  { file: 'Sepsis_ARDS_and_Cardiac_Arrest_Pharmacotherapy.m4a', title: 'Sepsis, ARDS, and Cardiac Arrest Pharmacotherapy', blurb: 'Vasopressor selection, lung-protective strategy, and the pharmacotherapy of a code.', area: 'Critical Care' },
  { file: 'Pharmacotherapy_Precision_for_Life-Threatening_Infections.m4a', title: 'Pharmacotherapy Precision for Life-Threatening Infections', blurb: 'Empiric-to-definitive therapy under pressure, when the wrong antibiotic costs a life.', area: 'Critical Care' },
  { file: 'HIV_Drug_Protocols_Diagnosis_and_Monitoring.m4a', title: 'HIV: Drug Protocols, Diagnosis, and Monitoring', blurb: 'ART regimen selection, resistance testing, and the monitoring schedule that catches problems early.', area: 'Infectious Disease' },
  { file: 'Infectious_Disease_Mastery_and_Stewardship_Essentials.m4a', title: 'Infectious Disease Mastery and Stewardship Essentials', blurb: 'Empiric therapy logic and the stewardship principles behind every antibiotic choice.', area: 'Infectious Disease' },
  { file: 'Managing_Seizures_Parkinson_s_Migraines_and_Stroke.m4a', title: "Managing Seizures, Parkinson's, Migraines, and Stroke", blurb: 'Antiepileptic selection, dopaminergic therapy, and acute stroke pharmacotherapy.', area: 'Neurology' },
  { file: 'Schizophrenia_Bipolar_and_Depression_Clinical_Audit.m4a', title: 'Schizophrenia, Bipolar, and Depression: Clinical Audit', blurb: 'Antipsychotic and mood-stabilizer selection audited against real clinical scenarios.', area: 'Psychiatry' },
  { file: 'The_Toxic_Trade-offs_of_Psychiatric_Drugs.m4a', title: 'The Toxic Trade-offs of Psychiatric Drugs', blurb: 'The adverse-effect calculus behind every psychiatric medication choice.', area: 'Psychiatry' },
  { file: 'Precision_Pharmacotherapy_for_Complex_Endocrine_Cases.m4a', title: 'Precision Pharmacotherapy for Complex Endocrine Cases', blurb: 'Diabetes, thyroid, and adrenal pharmacotherapy where the guideline answer isn’t obvious.', area: 'Endocrinology' },
  { file: 'The_Triple_Whammy_Kidney_Failure_Case.m4a', title: 'The Triple Whammy: A Kidney Failure Case', blurb: 'The classic NSAID/ACEi-ARB/diuretic interaction that tips a patient into AKI.', area: 'Nephrology' },
  { file: 'Stress_Testing_Asthma_and_COPD_Treatment_Plans.m4a', title: 'Stress-Testing Asthma and COPD Treatment Plans', blurb: 'GOLD and GINA stepwise therapy pressure-tested against real exacerbation scenarios.', area: 'Pulmonology' },
  { file: 'The_Oncology_Supportive_Care_Stress_Test.m4a', title: 'The Oncology Supportive Care Stress Test', blurb: 'Nausea, neutropenic fever, and the supportive-care decisions that run alongside chemo.', area: 'Oncology' },
  { file: 'Navigating_the_Geriatric_Pharmacotherapy_Minefield.m4a', title: 'Navigating the Geriatric Pharmacotherapy Minefield', blurb: 'Polypharmacy, Beers Criteria, and deprescribing in the patients most likely to be harmed.', area: 'Geriatrics' },
  { file: '2024_Clinical_Updates_in_Pediatric_Pharmacotherapy.m4a', title: '2024 Clinical Updates in Pediatric Pharmacotherapy', blurb: 'Weight-based dosing pitfalls and what changed in pediatric pharmacotherapy.', area: 'Pediatrics' },
  { file: 'Clinical_Cases_in_Sexual_and_Reproductive_Pharmacotherapy.m4a', title: 'Clinical Cases in Sexual and Reproductive Pharmacotherapy', blurb: 'Contraception, pregnancy safety categories, and reproductive-health pharmacotherapy cases.', area: 'Reproductive Health' },
  { file: 'Why_Normal_Lab_Results_Can_Kill.m4a', title: 'Why Normal Lab Results Can Kill', blurb: 'The lab values that look reassuring but mean something dangerous in context.', area: 'Drug Information' },
  { file: 'Spotting_Statistical_Smokescreens_in_Clinical_Trials.m4a', title: 'Spotting Statistical Smokescreens in Clinical Trials', blurb: 'How trials disguise a weak result — composite endpoints, subgroup fishing, and relative-risk framing.', area: 'Biostatistics' },
  { file: 'The_Architecture_of_Medical_Evidence.m4a', title: 'The Architecture of Medical Evidence', blurb: 'The evidence hierarchy and study-design reasoning tested on every biostatistics question.', area: 'Biostatistics' },
  { file: 'Clinical_Evidence_and_Health_Communication_Frameworks.m4a', title: 'Clinical Evidence and Health Communication Frameworks', blurb: 'Translating evidence into patient counseling and system-level health communication.', area: 'Healthcare Systems' },
  { file: 'How_medical_systems_prevent_fatal_errors.m4a', title: 'How Medical Systems Prevent Fatal Errors', blurb: 'Medication-error prevention, reporting systems, and the safety infrastructure of modern pharmacy practice.', area: 'Healthcare Systems' },
];
