/* Generate app/data.js from the corrected content banks in assets/data/*.json.
   Data lives in the JSON files (edit those); this bundles them as window globals
   the app reads synchronously. Run before serving or as the deploy build step. */
const fs = require('fs');
const path = require('path');
const DATA = path.join(__dirname, '..', 'assets', 'data');
const OUT = path.join(__dirname, '..', 'app', 'data.js');

const map = {
  __quizData: 'quiz.json', __flashData: 'flash.json', __accpData: 'accp.json', __conceptData: 'concept.json',
  __DRUG_DB: 'drug_db.json', __GLO_TERMS: 'glo_terms.json', __evidenceData: 'evidencedata.json',
  __studyChapters: '_studychapters.json', __epDrills: 'epdrills.json',
};

let out = '/* Generated by scripts/build-data.js from assets/data/*.json — do not edit by hand. */\n';
for (const [g, f] of Object.entries(map)) {
  const arr = JSON.parse(fs.readFileSync(path.join(DATA, f), 'utf8'));
  const clean = Array.isArray(arr) ? arr.filter(x => x != null) : arr; // drop any array holes
  out += `window.${g} = ${JSON.stringify(clean)};\n`;
}
fs.writeFileSync(OUT, out);
console.log('Wrote app/data.js (' + (out.length / 1024 | 0) + ' KB) from ' + Object.keys(map).length + ' banks.');
